AddingPowerSupport_CI/Testing
pkg/sftp pull request #400
Opened 2020-12-07 07:29 UTC by santosh653

Adding power support.,

Adding power support ppc64le with Continues Integration/testing so that code remains architecture independent.

This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

The build is successful on both arch: amd64/ppc64le, please find the Travis Link below.
https://travis-ci.com/github/santosh653/sftp

Please let me know if you need any further details.

Thank You !!
@santosh653

2020-12-08 10:28 UTC, drakkan approved these changes

2020-12-08 10:30 UTC, drakkan commented
LGTM, maybe we should also enable testing on arm64 in a separate commit

2020-12-08 12:04 UTC, drakkan commented
In general I'm not very happy with travis, it is really slow. For example I submitted a PR more than an hour ago and the build is not started yet. I would like to switch to GitHub actions

2020-12-08 13:46 UTC, drakkan requested changes
Before merging this PR I suggest to decide if accept #402 or continue to use travis

2020-12-08 16:15 UTC, santosh653 commented
@drakkan Thanks for your updates, As for now we will continue to use Travis. Not sure but Builds on Travis look ok in terms of running time barring couple of instances.
Hope this answers your query.
Thank You !!

2020-12-08 16:31 UTC, drakkan commented
> @drakkan Thanks for your updates, As for now we will continue to use Travis. Not sure but Builds on Travis look ok in terms of running time barring couple of instances.
> Hope this answers your query.
> Thank You !!

@santosh653 the question was not for you but for other pkg/sftp maintainers, sorry for the confusion. 

Currently using travis is really unpleasant. For example today I submitted a PR that introduced a regression on macOS, I had to wait for an hour or more for Travis to build my changes. I added a github action to my repo and fixed the bug much faster.

So we should switch to travis.com or to github actions

2020-12-08 18:09 UTC, gerrith3 commented
@drakkan you definitely want to get off of travis-ci.ORG - they announced they were deprecating it about two years ago.  They are now slowing down jobs there to send the message to move.   Not sure if the message is clear enough, but there are no delays in starting jobs on travis-ci.COM unless there is a serious overload somewhere (which I doubt).

2020-12-08 18:52 UTC, drakkan commented
> @drakkan you definitely want to get off of travis-ci.ORG - they announced they were deprecating it about two years ago. They are now slowing down jobs there to send the message to move. Not sure if the message is clear enough, but there are no delays in starting jobs on travis-ci.COM unless there is a serious overload somewhere (which I doubt).

Yes, as said above and in #402 we should switch to travis-ci.com or github actions. I think we have to wait for the opinion of other pkg/sftp maintainers as well, #402 is the right issue for discussing about this, thank you for your patience

2020-12-09 16:22 UTC, puellanivis commented
:woman_shrugging: sounds like Github actions might be the best choice going forward.

2020-12-11 16:13 UTC, santosh653 commented
Are there any queries open on this PR?

2020-12-12 12:15 UTC, drakkan commented
> Are there any queries open on this PR?

No thank you for your effort. 

We (authors and maintainers of pkg/sftp) should decide whether to accept this PR and continue using travis (switching to travis-ci.com) or reject the PR and move on to GitHub actions, thanks for your patience

2020-12-23 14:26 UTC, santosh653 commented
Do we have any further queries on this PR? Is this PR getting merged?

2020-12-29 14:51 UTC, drakkan commented
> Do we have any further queries on this PR? Is this PR getting merged?

Hi,

I would prefer to merge #402, I added support to run tests on aarch64, ppc64le and armv7

2020-12-31 15:55 UTC, puellanivis commented
I suppose that I am fine with either. We just need to decide.

2021-01-20 12:59 UTC, drakkan commented
Hi, we switched to GitHub Actions so this PR cannot be merged, sorry

2021-01-20 12:59 UTC, closed without merging